apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monica
  namespace: monica-app
spec:
  interval: 5m
  chart:
    spec:
      chart: monica
      version: 7.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      TZ: "Europe/Berlin"
      APP_URL: https://monica.${SECRET_DOMAIN}
      APP_KEY: ${SECRET_MONICA_APP_KEY}
      DB_HOST: monica-mariadb.monica-app.svc.cluster.local
      DB_DATABASE: monica
      DB_USERNAME: monica
      DB_PASSWORD: ${SECRET_MONICA_DB_PASSWORD}

    ingress:
      main:
        enabled: true
        hosts:
          - host: "monica.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

    persistence:
      config:
        enabled: true
        storageClass: longhorn

    mariadb:
      enabled: true
      auth:
        database: monica
        username: monica
        password: ${SECRET_MONICA_DB_PASSWORD}
        rootPassword: ${SECRET_MONICA_DB_ROOT_PASSWORD}
      primary:
        nodeSelector:
          beta.kubernetes.io/arch: amd64

        persistence:
          enabled: true
          storageClass: longhorn
          size: 2Gi
