apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi-app
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: 4.8.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      TZ: Europe/Berlin

    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: "unifi"
          metallb.universe.tf/loadBalancerIPs: ${UNIFI_LB_ADDRESS}
        ports:
          http:
            port: 8443
            protocol: HTTPS
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          speedtest:
            enabled: true
            port: 6789
            protocol: TCP
          stun:
            enabled: false
          syslog:
            enabled: false
          discovery:
            enabled: false
      udp:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: "unifi"
          metallb.universe.tf/loadBalancerIPs: ${UNIFI_LB_ADDRESS}
        ports:
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP

    ingress:
      main:
        enabled: true
        hosts:
          - host: "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

    persistence:
      data:
        enabled: true
        storageClass: longhorn-encrypted
        size: 1Gi
        accessMode: ReadWriteOnce
