apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: calibre-app
spec:
  interval: 5m
  chart:
    spec:
      chart: calibre-web
      version: 8.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    nodeSelector:
      kubernetes.io/arch: amd64

    image:
      tag: version-0.6.18

    env:
      TZ: "Europe/Berlin"
      DOCKER_MODS: linuxserver/calibre-web:calibre

    ingress:
      main:
        enabled: true
        hosts:
          - host: "calibre.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

    persistence:
      config:
        enabled: true
        storageClass: longhorn-encrypted
        size: 100Mi
        accessMode: ReadWriteOnce
      books:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SECRET_NAS_ADDRESS}"
            path: /share/calibre
