apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  # Cluster configuration
  METALLB_RANGE: 10.0.0.240-10.0.0.250

  # Network
  GATEWAY_ADDR: 10.0.0.1
