apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:KkCt/KSh6MM=,iv:T4CyG+RG7JuSyDtjb0ZlwiJeDszw2tKkCsC3c7yP3sQ=,tag:wgr6aKp7G8NvwRQWDWLHow==,type:str]
    SECRET_CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:5QrwhX+R/C/o8N5aROaLoSqXVghUPDz5AXjDM4+UtErRGFfD8HeXQQ==,iv:xGnIbYeLhQ80pMLTt0owStaaUdvIV+QjmBRA2Mhcxjg=,tag:oUmgWBHL4L5KnNsT1ILJjw==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:xi/vyLcTYxP8u/mj5ARBGZ+jXAd/xaIHr08fyJS5bK859iBXS/CfR7QsqojsikuWu0x24ftYq2h0WolgeNKbyA==,iv:Zu5jwFG7iP/oC27AWYD1mF9BYrNdHcNWQJtUrlGXO6g=,tag:fH5DhUIfYHQMB10t0863YA==,type:str]
    SECRET_NAS_ADDRESS: ENC[AES256_GCM,data:sFKq7BdwCSSE,iv:Y2jYA24Pc1/8+68w4V0Y5jLjZuN2zaufoxwYo6UsL2M=,tag:JMCH1QFi8AzIXk0X3P5ybw==,type:str]
    SECRET_PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:W7f9phs=,iv:2K38wIymynzg8Ex/qBFx90WNtxy9gHCYZpYXPJKAqlY=,tag:EmcYyIzZZio+2LDtFB5PfQ==,type:str]
    SECRET_BACKBLAZE_BACKUP_TARGET: ENC[AES256_GCM,data:8FjbwDeB4lGMOJ3uhGquXcmX0devr7I85GX6IIv/MjLmyL7vEf31yR0bwg==,iv:gpnKPcLNhFXPv56bJnyI9vSVvsZapL6c5KwqRuZb8XA=,tag:BslEMdNYSHKiORNTectkpQ==,type:str]
    SECRET_GOTIFY_PASSWORD: ENC[AES256_GCM,data:RHCRxnJOX6O856GUa4VeRfSRxqzK6BC3qnTA18DDv+7l+Nbj9cHAu4ol5Hp96xTHfX3bCHqm1gKdCTV48lUL0Q==,iv:pLlHdLypICXBNCEH5xTt8G4nxkMdcRrVLkKugaKQT90=,tag:W43vuv2n/u8qJF2zWAxoOg==,type:str]
    SECRET_ADGUARD_PASSWORD: ENC[AES256_GCM,data:CeCbgadJLbIAfPealVMVpln1Kns44cQRJz2axCcc8JhYwrW5x+ziJZqVWyH1rus4tDL5XSQOHoBR2Wd+,iv:n8GEIEwKlRti3R6KIFxJaasSuf1q9P39pmUoh2KWSVc=,tag:SLj/YC/BZY+NP8dCgmPcSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19a7eacuhstswjez4da59c7vufjgye3xxkdnkczewj2ccrqjt4v0s02zcxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NU11dGxiMzBHTFRSSkFt
            bWV6cHVhUHNOVjdKdTAwckxFZjBkYlREUUFBCkRGeGVnMFA4NU1KcW1uNU1rVDNu
            OHk5RUpoNW9XbEJQaTFtck9qRlg0QkUKLS0tIE02VEIzVkpKaHFjbTJLZmZoeWYz
            WXMrWFRISnNLNmY5ejVBV0FXSGxtUG8KP4UWG3maxkdntze7elLsgyYMp9ZDXypY
            oi1W0pdj9QUaHq30s+2QDHfyBlpXnKjKy4OHKrhKR6hTaWGr5wmYWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-18T18:07:16Z"
    mac: ENC[AES256_GCM,data:aK77xCGIYLUtiKD2D9LcZzwWBhVncQvVB4UfBT82df7Mj+bXGH/MrOWEpv4jLvjrrhkGMqEmBnv9YQ/4izZsYe6atPRzLwVXPXXL+4lDfjxTjYjYmq1nVClC/xtShk57xf5HzW2zngMPPG/rp4u1yiQfkT3BOrim7sAmt0tanZQ=,iv:MEEbNBmbTksTbpEdkU8mZoLD5cBIxgUZtIrto6dxfV4=,tag:oY2TWs6TIcd8PtpuDl77Ew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
