apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:DeEhLHPwyV4=,iv:rhLoI7L8M41uwNkjJLRm3lansH3YN5MnalzbSt0XBng=,tag:4AyOngefq/3WA7/tnxIuPg==,type:str]
    SECRET_CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:kAMyv4u/lEyUsk3rl4APsTe547uZIlIrGG13+Iq7GKh+YkDIB+sSiQ==,iv:Tm3RwHF6XqYMGKUwmV5OGPueXrOEdgR0mHrL0EqGRpY=,tag:GG4+dkFQHFKreIZ4ZFU28g==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:45AnZnxRTPtnV/IQAqAigPXVf8FwWvjNsvAjlIhtFri+3YEdHOjg3QgLk/dqQX3cdAa71cLzqPQ7xk1j+qUiGQ==,iv:t7JFVuj70RjSt/lq5MSjT+Ufb7MFCZLp15hOSHIEBTU=,tag:Q0JycY58vXvLy9YNfeoDBw==,type:str]
    SECRET_NAS_ADDRESS: ENC[AES256_GCM,data:6EH54jopBpr3,iv:2OQn6q/wTELbBMK8aRw42d9boUogMSUQRN6+mZq8DVs=,tag:1IQJH+cyfHjdRsDS5cIwjQ==,type:str]
    SECRET_PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:O2QueBw=,iv:/KVf0Qwr7dbILIq7ezJpQ44SA++b/OpMW7q9HqdOHUM=,tag:suRaa9MmWCvTJM631fPMAg==,type:str]
    SECRET_BACKBLAZE_BACKUP_TARGET: ENC[AES256_GCM,data:Ky6sUCdZMlYB9ZD5S3NOgBCERdCjaWlFje9qoAX6SB/67qRWYiOOay/ltA==,iv:BVoc29rYeveCLSaPjgs+CuzJBmSh/u120WMXSO0jkOE=,tag:pw+OkJ6kzCJS6SWFXo3esg==,type:str]
    SECRET_GOTIFY_PASSWORD: ENC[AES256_GCM,data:piZfRVXtdxL9n+9UmXGtK1uwu+MS3FlVofrgXD3mLFRFG5X5HYFZOPfd/dGSAPI2aNPKOLOWketS4cs4+AhIIg==,iv:Pq1rFuU1qAsJ3FjDcp1vPrMxQ4HOIRJyV+4oo5G/71A=,tag:2AwtsxFayF6n1D3yMUrRmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19a7eacuhstswjez4da59c7vufjgye3xxkdnkczewj2ccrqjt4v0s02zcxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YVdNcVpMZGREa2VhN2Rz
            aGFHVVFJMWlPZzFUa1VNYzBQZndBbzFrb1Q4ClpvV1RzMkZRY3hQbUhOWVhYcmR6
            RXVxTTRKQks3U1B6THgrWGtMdDBGOWMKLS0tIGg4Qk43cHZkb21FWnNadWFFc3kz
            SUtJYzdTWWZ0UmY5OTkyUzNuSUxMN1EKB3BmIYsfCxol7wEa+1DYctHN8iUmlgMw
            DSR4P/l9MBSARxiB3RlmCU1PkGXVHpF0bWO8bHp+SbSl+vcPU+010A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-18T16:22:16Z"
    mac: ENC[AES256_GCM,data:23BrbrJKY1TIfgARHYTpyMteHe5O/EToGp8keLeEp6sq5U/jEmzdbSWZ5M+CmnubXosxnuO3CHQCCyhUcBCPXEeyl5GZNdqW867vFxc9m10q09JQK7HVXJDBLPZnbnKc4+NvDs9zPz5McLnExsGaoB9WppgcZb0By6PMVwKVv6Q=,iv:2XFBcblt160Lz1zKe8udft594LkK7Kvld3PEW7+ZMfM=,tag:w5RtGkGmc1aZfoS0loklew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
