apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:W0DbOmdj1II=,iv:SJitFE8kQTpob5U9P1mFdc1Y8wHWQvGh6GEVSZ2mG/I=,tag:7w4p3pjIIYe3thjuuokB1A==,type:str]
    SECRET_CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:tHt3h8yy/Thhda6wgVaopRNL7ClLl0DuEnkVcSdvMJIIOvovHFOvTw==,iv:vGUztHFWOQjATsDUGFV3qFNCt4qd284qcQsEzSOsz4w=,tag:zCg0yraHXQuZkNX3GlSFug==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:fKmKoAPBkuBAmKkQC596aTSjGW3s7rIM4Z3AhvKTN218SG9Y8N7PSDU/58ja2/g3w9stoExOhvuk1563LmieJw==,iv:liGcFU/D1yPzneqTyvH5dZrqEdvyxAaTMSvR5PisYBw=,tag:kU6ttdnr8YnOfE+7KvyjHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19a7eacuhstswjez4da59c7vufjgye3xxkdnkczewj2ccrqjt4v0s02zcxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ0J6M3dWcmhqUVVnajY1
            NjZDVm10RFkyUW80U0gxcjlQVEdiTFdIYjA4CjhhWjBFc0ZlQjNpQnZGNUNTNktt
            b2ZLaVNXVnZWcTJMVnp3eWI1c2QrVGMKLS0tIHRWVFRNWlVSS1BhZC9COHJxR0JQ
            VW1sUHQvTWxDU24yeGJrQlFzRUt0NEEKHS4C6A097J8cyT63zMIAgqrOfPVPFHCq
            G9cKsVYi0ZjHcDGSw85DijEtMw1Sh5gCPC1H+CmwPNb/tT1U7tMbAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-13T17:18:00Z"
    mac: ENC[AES256_GCM,data:DGWckFIIhB0XIb38QAT99s4u40QKRo1x0BXQKyXXqExxTIUHHofOfz8a80Lk5ohJ7X/V6WUfphww/1BLpkKi8i59l9v6uTfA+yN3FDPJ59Ht4Y6/Dqeh0y2fGzA8e+JOZ/g42TxLucMB/AZoLw+0X3wmwCWmjjFSlx2mHwH2VME=,iv:UA2MIQv5q7W1H0mTOZ+7lQ+LlJFsH8S1GE8+VaSBeO0=,tag:8rvSflD6JumNxCvVhnqSbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
