apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:9gpio+LiIDo=,iv:ACEjxo2TKTwq4wZjn7kvFTrYw7juTtta2y15BHxi6is=,tag:z4Hz+67LaDev/t5wE6xK/Q==,type:str]
    SECRET_CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:LixMNnWZgy90EMHF3PX0P32KZCowJA/NaYy6qw66Ye0TY8ec3MbnFA==,iv:Pc3X7Hn1f7VgWgKuIas4vz20XHuOO+oJF3FyxTh7lro=,tag:nRolmDwtyVx1NsiVo4ouqg==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:QGQH1RzL5VY8m9G9H1KESQ6oFom5QYC5URqTReSA09HuGB1JC11X/WowSj41xcbKqRp6hHmto3d7DW6mRenKVQ==,iv:VgljJ97MMQkRZNJZqn2yk06OEAFMq6EQm1MvjEe5iTg=,tag:bE6dryr2kYaaX58149PV/A==,type:str]
    SECRET_NAS_ADDRESS: ENC[AES256_GCM,data:pMBnYwOhKSNd,iv:AdDRepAc4zHNyauCPzg5mtFeE/952xriCLheAkV8r98=,tag:j+rS/sm3SgwXkKP/JLmfYw==,type:str]
    SECRET_PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:jhc6ZC0=,iv:Js+/5eHUep7n+ahdp0FPCt7x5VhjIOn1OtCQF5xPRQo=,tag:/QJJDyOSnd4FLr5B4luBIA==,type:str]
    SECRET_BACKBLAZE_BACKUP_TARGET: ENC[AES256_GCM,data:tmkUoCRyeAm02whYbJki+F45cWPPPzt2pE7Wdu7s2xxiqEAC+d++VTueng==,iv:JbiVCKQNd3qVwGU1uQlY0s7PhAgkAEGOHbJgiSn2P7w=,tag:Oa6Z9RlzcsuZUdP1jy1OCg==,type:str]
    SECRET_GOTIFY_PASSWORD: ENC[AES256_GCM,data:VTxFvj5vBqUHRg07FUScuDUOo8Uvdww1Z/8tLCgfpjgzuWsApAS2Gf/Grib9vanLPUz3ObOgSv9qAwRa417nFA==,iv:4CP73cddr4gXHYAhOIvqkOdZsc2m60ljtY+ebRrjl1w=,tag:kaNzyv9lN0XKO/5x/R2NjQ==,type:str]
    SECRET_ADGUARD_PASSWORD: ENC[AES256_GCM,data:s09FNdMtLFx50J4VcfmOCG6nYRrXI9yHuKjslqzqOI1aPG2hUuKrfPiCNMSYoEkL0SOfiPjQYhOBKPiK,iv:fv6cQcI2VdAFqcKcAP3TzhEzhX/1f+yzeeDBwPhyiws=,tag:9y+RpsvTQbvFEtFaLD0TWA==,type:str]
    SECRET_MONICA_APP_KEY: ENC[AES256_GCM,data:lFcRRZtGFyrDUrXHTc02UVt3rW29m7iu0cnnrItPVRsmPDvieC0ECGp4OZeCmwm7mGut,iv:nr6+R54XzWLklGLfFHlg5xitXCSsTTmHgcXi4HaaFaQ=,tag:9uhX99UNzV+J1uuhAomBFg==,type:str]
    SECRET_MONICA_DB_PASSWORD: ENC[AES256_GCM,data:9fsHazdaQ3Zyo0rkV8STo7Y1BSmqPXtYytDHXtnrVCXgyjVRyC/4ct5G3gUjvl97+xjFIzXDefM=,iv:Pw/NxDYFzhBT3OaPkClxSYc5XsFidmtI3T3w7yEt40c=,tag:f2wgBxllIcxs3+Ex51lASg==,type:str]
    SECRET_MONICA_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:KIu4n44n7qyWxTMsRVF0JgoeTfATUaImHVpq2niWihrLrKF4scEM4cAh+KxZxbkhPSvo5jf9Yng=,iv:7xBRw5j9Zux04ubJW+trBG9a5+oFXkFbHJ9ykDHpNfs=,tag:gJlhNXw/HNTDs8kKv3mjOg==,type:str]
    SECRET_IP_CAMERA_TERRASSE: ENC[AES256_GCM,data:RrVSlXtgjX0M,iv:f85QAUgO2L0lAHY6sLC+SuSQ9Ov40/xD2/LRRhVAKgE=,tag:oejtfIDrpHWHD1atbS8ofw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19a7eacuhstswjez4da59c7vufjgye3xxkdnkczewj2ccrqjt4v0s02zcxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRnczcVhrWTNhZ2t2ZFJv
            NW1JZTVCaG5DZVAxcUt5THVqL3RWSyt3RTMwCkY1OW9PTW9WbkZhMzZvMWV2QnhW
            a1Npb1RNSk1ZWXVLbGlreTFuaUkzZVUKLS0tIFFjWHpNbGFvS3lXM1N0djN5UW9i
            SFgrVk9WQVF4SDlmY2p5QnRyTzJFNFkKk1SrctlSkBpcB6M3UtQvLXvmfIlBt2bK
            wByeE3/DV9lX5GCTkA75Y+aY60t2ZBQkzJNtA2s2E/oGhLpupHQhqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-23T20:09:13Z"
    mac: ENC[AES256_GCM,data:0Sk1OgBxr/5bMKycS2ZxdiFgqC7iZ3SlJGjr+o699K76azJ5P4Us4yQRXoLHIXQToyT8SNO28hcQrhrLKg51XGCjKvY7Am55M8TTYG7xQlYme5SvcVkp1DZPkbsthmNmUWx5+t/MGuJmF5vUpdbx5pX2t5yVQo8frEb4jL4/NkA=,iv:sWtR9jDDMj+aQKHw91/yEc4G14AGSLLk1IM3HKey6d4=,tag:BlNkNsYBvMPSwvP7PjG78A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
