apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.2.4
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    ingress:
      enabled: true
      host: longhorn.${SECRET_DOMAIN}
    defaultSettings:
      backupTarget: ${SECRET_BACKBLAZE_BACKUP_TARGET}
      backupTargetCredentialSecret: backblaze-credentials
      backupstorePollInterval: 3600 #every hour
