apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  - "${METALLB_RANGE}"
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: layer2
