apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gotify
  namespace: gotify-app
spec:
  interval: 5m
  chart:
    spec:
      chart: gotify
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: gotify/server-arm64

    env:
      TZ: "Europe/Berlin"
      GOTIFY_DEFAULTUSER_NAME: admin
      GOTIFY_DEFAULTUSER_PASS: ${SECRET_GOTIFY_PASSWORD}

    ingress:
      main:
        enabled: true
        hosts:
          - host: "gotify.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

    persistence:
      data:
        enabled: true
        storageClass: longhorn
        size: 100Mi
        accessMode: ReadWriteOnce

    nodeSelector:
      beta.kubernetes.io/arch: arm64
