apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: sabnzbd-app
spec:
  interval: 5m
  chart:
    spec:
      chart: sabnzbd
      version: 9.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/sabnzbd
      tag: v3.6.0

    env:
      TZ: "Europe/Berlin"

    ingress:
      main:
        enabled: true
        hosts:
          - host: "sabnzbd.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      supplementalGroups:
        - 100

    persistence:
      config:
        enabled: true
        storageClass: longhorn-encrypted
        size: 100Mi
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SECRET_NAS_ADDRESS}"
            path: /share/sabnzbd/media
        mountPath: /media
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${SECRET_NAS_ADDRESS}"
            path: /share/sabnzbd/downloads
        mountPath: /downloads
