apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant-app
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 13.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      TZ: Europe/Berlin

    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet

    service:
      main:
        type: LoadBalancer

    ingress:
      main:
        enabled: true
        hosts:
          - host: "homeassistant.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 500Mi
